bond = {
    'BND': 'US BOND',
    'TLT': 'US TREASURY',
    'BNDX': 'WORLD BOND',
}

index = {
    'SPY': 'SP 500',
    'VWRD.L': 'MSCI WORLD',
    '^FCHI': 'CAC 40',
    '^GDAXI': 'DAX 40',
    '^N225': 'NIKKEI 225',
    'IXUS': 'WORLD EX-US',
    'VWO': 'EMERGING MARKETS',
}

index_mid = {
    'SPY': 'S&P 500',
    'VWRD.L': 'MSCI World',
    '^FCHI': 'CAC 40',
    '^GDAXI': 'DAX 40',
    '^N225': 'Nikkei 225',
    '^HSI': 'Hang Seng Index',
    '^FTSE': 'FTSE 100',
    '^DJI': 'Dow Jones Industrial Average',
    '^GSPC': 'S&P 500',
    'EFA': 'iShares MSCI EAFE ETF',
    'EEM': 'iShares MSCI Emerging Markets ETF',
    '^KS11': 'KOSPI',
    '^BVSP': 'BOVESPA',
    '^AORD': 'All Ordinaries',
    '^BSESN': 'BSE SENSEX',
    '^JKSE': 'Jakarta Composite Index',
    '^TWII': 'Taiwan Weighted',
    '^STI': 'Straits Times Index',
    '^MERV': 'MERVAL',
    '^MXX': 'IPC Mexico',
    '^NZ50': 'NZX 50',
    '^XAX': 'NYSE AMEX Composite Index',
    '^XMI': 'NYSE ARCA Major Market Index',
    '^RUT': 'Russell 2000',
    'MDY': 'SPDR S&P MidCap 400 ETF Trust',
    # '^SML': 'S&P SmallCap 600',
}

crypto = {
    'BTC-USD': 'BTC',
    'DOGE-USD': 'DOGE',
    'ETH-USD': 'ETH',
    'XRP-USD': 'XRP',
    'ADA-USD': 'ADA',
}

crypto_mid = {
    'BTC-USD': 'Bitcoin',
    'ETH-USD': 'Ethereum',
    'XRP-USD': 'XRP',
    'LTC-USD': 'Litecoin',
    'BCH-USD': 'Bitcoin Cash',
    'ADA-USD': 'Cardano',
    'XLM-USD': 'Stellar',
    'LINK-USD': 'Chainlink',
    'BNB-USD': 'Binance Coin',
    'USDT-USD': 'Tether',
    'EOS-USD': 'EOS',
    'TRX-USD': 'TRON',
    'ETC-USD': 'Ethereum Classic',
    'NEO-USD': 'NEO',
    'DASH-USD': 'Dash',
    'ZEC-USD': 'Zcash',
    'XMR-USD': 'Monero',
    'VET-USD': 'VeChain',
    'DOGE-USD': 'Dogecoin',
    'OMG-USD': 'OMG Network',
    'QTUM-USD': 'Qtum',
    'BAT-USD': 'Basic Attention Token',
    'LSK-USD': 'Lisk',
    'REP-USD': 'Augur',
    'ICX-USD': 'ICON',
    'ZRX-USD': '0x',
    'STEEM-USD': 'Steem',
    'DGB-USD': 'DigiByte',
    'ONT-USD': 'Ontology',
    'WAVES-USD': 'Waves',
    'MAID-USD': 'MaidSafeCoin',
    'SC-USD': 'Siacoin',
    'PPT-USD': 'Populous',
    'KMD-USD': 'Komodo',
    'SNT-USD': 'Status',
    'GNT-USD': 'Golem',
    'FUN-USD': 'FunFair',
    'ELF-USD': 'aelf',
    'ARK-USD': 'Ark',
    'SYS-USD': 'Syscoin',
    'ANT-USD': 'Aragon',
    'STORJ-USD': 'Storj',
    'MANA-USD': 'Decentraland',
    'GAS-USD': 'Gas',
    'PAY-USD': 'TenX',
    'MTL-USD': 'Metal',
    'CVC-USD': 'Civic',
    'PIVX-USD': 'PIVX',
    'NXS-USD': 'Nexus',
}

crypto_xl = {
    'BTC-USD': 'Bitcoin',
    'ETH-USD': 'Ethereum',
    'BNB-USD': 'Binance Coin',
    'ADA-USD': 'Cardano',
    'XRP-USD': 'XRP',
    'DOGE-USD': 'Dogecoin',
    'DOT1-USD': 'Polkadot',
    'UNI3-USD': 'Uniswap',
    'SOL1-USD': 'Solana',
    'LINK-USD': 'Chainlink',
    'MATIC-USD': 'Polygon',
    'ETC-USD': 'Ethereum Classic',
    'LTC-USD': 'Litecoin',
    'XLM-USD': 'Stellar',
    'THETA-USD': 'Theta Token',
    'VET-USD': 'VeChain',
    'EOS-USD': 'EOS',
    'TRX-USD': 'TRON',
    'AAVE-USD': 'Aave',
    'COMP-USD': 'Compound',
    'FIL-USD': 'Filecoin',
    'XMR-USD': 'Monero',
    'XTZ-USD': 'Tezos',
    'HT-USD': 'Huobi Token',
    'DCR-USD': 'Decred',
    'ZEC-USD': 'Zcash',
    'BAT-USD': 'Basic Attention Token',
    'NEO-USD': 'NEO',
    'MKR-USD': 'Maker',
    'DASH-USD': 'Dash',
    'KSM-USD': 'Kusama',
    'WAVES-USD': 'Waves',
    'ICP-USD': 'Internet Computer',
    'BTT-USD': 'BitTorrent',
    'GRT-USD': 'The Graph',
    'REN-USD': 'Ren',
    'HNT-USD': 'Helium',
    'ZIL-USD': 'Zilliqa',
    'OMG-USD': 'OMG Network',
    'SNX-USD': 'Synthetix',
    'SUSHI-USD': 'SushiSwap',
    'QTUM-USD': 'Qtum',
    'ENJ-USD': 'Enjin Coin',
    'DGB-USD': 'DigiByte',
    'YFI-USD': 'yearn.finance',
    'CRV-USD': 'Curve DAO Token',
    'ONE2-USD': 'Harmony',
    'SC-USD': 'Siacoin',
    'LEO1-USD': 'UNUS SED LEO',
    'XEM-USD': 'NEM',
    'RVN-USD': 'Ravencoin',
    'LSK-USD': 'Lisk',
    'CEL-USD': 'Celsius',
    'BTG-USD': 'Bitcoin Gold',
    'ZEN-USD': 'Horizen',
    'HBAR-USD': 'Hedera Hashgraph',
    'ONT-USD': 'Ontology',
    'SXP-USD': 'Swipe',
    'BNT-USD': 'Bancor',
    'CRV-USD': 'Curve DAO Token',
    'REP-USD': 'Augur',
    'CHZ-USD': 'Chiliz',
    'TUSD-USD': 'TrueUSD',
    'BUSD-USD': 'Binance USD',
    'HUSD-USD': 'HUSD',
    'USDT-USD': 'Tether',
    'USDC-USD': 'USD Coin',
    'DAI-USD': 'Dai',
    'AMPL-USD': 'Ampleforth',
    'USDK-USD': 'USDK',
    'GUSD-USD': 'Gemini Dollar',
    'SUSD-USD': 'sUSD',
    'TBTC-USD': 'tBTC',
}

commodity = {
    'GC=F': 'GOLD',
    'SI=F': 'SILVER',
}

commodity_mid = {
    'GC=F': 'Gold',
    'SI=F': 'Silver',
    'CL=F': 'Crude Oil',
    'NG=F': 'Natural Gas',
    'HG=F': 'Copper',
    'ZC=F': 'Corn',
    'ZS=F': 'Soybeans',
    'ZW=F': 'Wheat',
    'CT=F': 'Cotton',
    'KC=F': 'Coffee',
    'SB=F': 'Sugar',
    'OJ=F': 'Orange Juice',
    'LE=F': 'Live Cattle',
    'HE=F': 'Lean Hogs',
    # 'LB=F': 'Lumber',
    'PL=F': 'Platinum',
    'PA=F': 'Palladium',
    'RB=F': 'RBOB Gasoline',
    'HO=F': 'Heating Oil',
    'LBS=F': 'Random Length Lumber',
    'ETH=F': 'Ethanol',
    'CC=F': 'Cocoa',
    # 'SM=F': 'Soybean Meal',
    # 'BO=F': 'Soybean Oil',
    'GF=F': 'Feeder Cattle',
    # 'RR=F': 'Rough Rice',
}

stock = {
    'AAPL': 'Apple Inc.',
    'NVDA': 'NVIDIA Corporation',
    'LVMUY': 'LVMH Moët Hennessy Louis Vuitton SE',
}

stock_xl = {
    'AAPL': 'Apple Inc.',
    'MSFT': 'Microsoft Corporation',
    'AMZN': 'Amazon.com Inc.',
    'GOOGL': 'Alphabet Inc. (Google)',
    # 'FB': 'Meta Platforms Inc. (Facebook)',
    'TSLA': 'Tesla Inc.',
    'NVDA': 'NVIDIA Corporation',
    'JPM': 'JPMorgan Chase & Co.',
    'V': 'Visa Inc.',
    'PG': 'Procter & Gamble Co.',
    'JNJ': 'Johnson & Johnson',
    'UNH': 'UnitedHealth Group Incorporated',
    'MA': 'Mastercard Incorporated',
    'PYPL': 'PayPal Holdings Inc.',
    'DIS': 'The Walt Disney Company',
    'NFLX': 'Netflix Inc.',
    'HD': 'The Home Depot Inc.',
    'INTC': 'Intel Corporation',
    'CRM': 'Salesforce.com Inc.',
    'KO': 'The Coca-Cola Company',
    'PEP': 'PepsiCo Inc.',
    'CMCSA': 'Comcast Corporation',
    'BAC': 'Bank of America Corporation',
    'CSCO': 'Cisco Systems Inc.',
    'PFE': 'Pfizer Inc.',
    'T': 'AT&T Inc.',
    'VZ': 'Verizon Communications Inc.',
    'WMT': 'Walmart Inc.',
    'MRK': 'Merck & Co. Inc.',
    'NKE': 'NIKE Inc.',
    'ADBE': 'Adobe Inc.',
    'XOM': 'Exxon Mobil Corporation',
    'CVX': 'Chevron Corporation',
    'BA': 'The Boeing Company',
    'IBM': 'International Business Machines Corporation',
    'LMT': 'Lockheed Martin Corporation',
    'GM': 'General Motors Company',
    'TSM': 'Taiwan Semiconductor Manufacturing Company Ltd.',
    'ABNB': 'Airbnb Inc.',
    'SQ': 'Square Inc.',
    'ROKU': 'Roku Inc.',
    'AMD': 'Advanced Micro Devices Inc.',
    'UBER': 'Uber Technologies Inc.',
    'LYFT': 'Lyft Inc.',
    'ZM': 'Zoom Video Communications Inc.',
    'SNAP': 'Snap Inc.',
    'SPOT': 'Spotify Technology S.A.',
    'GS': 'The Goldman Sachs Group Inc.',
    'WFC': 'Wells Fargo & Company',
    'ROK': 'Rockwell Automation Inc.',
    'NOW': 'ServiceNow Inc.',
    'COIN': 'Coinbase Global Inc.',
    # 'TWTR': 'Twitter Inc.',
    'SQ': 'Square Inc.',
    'SHOP': 'Shopify Inc.',
    'LULU': 'Lululemon Athletica Inc.',
    'ABT': 'Abbott Laboratories',
    'SAP': 'SAP SE',
    'RACE': 'Ferrari N.V.',
    'AAL': 'American Airlines Group Inc.',
    'CAT': 'Caterpillar Inc.',
    'GE': 'General Electric Company',
    'MCD': 'McDonald\'s Corporation',
    'UBER': 'Uber Technologies Inc.',
    'JNJ': 'Johnson & Johnson',
    'AMZN': 'Amazon.com Inc.',
}

def get_assets(l):
    assets = dict()
    if 'stock' in l:
        assets.update(stock)
    if 'index' in l:
        assets.update(index)
    if 'commodity' in l:
        assets.update(commodity)
    if 'crypto' in l:
        assets.update(crypto)
    if 'bond' in l:
        assets.update(bond)
    if 'crypto_xl' in l:
        assets.update(crypto_xl)
    if 'stock_xl' in l:
        assets.update(stock_xl)
    if 'crypto_mid' in l:
        assets.update(crypto_mid)
    if 'index_mid' in l:
        assets.update(index_mid)
    if 'commodity_mid' in l:
        assets.update(commodity_mid)
    return assets